<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            'Agricultural products' => [
                'Farm Machinery & Equipment',
                'Meals & Drinks',
                'Livestock & Poultry',
                'Feeds, Supplements & Seeds',
            ],
            'Animals and Pets' => [
                'Birds',
                'Cats & Kittens',
                'Dogs & Puppies',
                'Fish',
                'Pet Accessories',
                'Reptiles',
                'Other Animals',
            ],
            'Apparel and Clothing' => [
                "Men's Clothing",
                "Women's Clothing",
                "Men's Plus Size",
                "Women's Plus Size",
            ],
            'Baby, Kids, Maternity and Toys' => [
                'Baby & Kids Clothing',
                'Remote Control Line',
                'Stuffed Animals & Plush Toys',
                'Accessories',
                'Shoes',
                'Novelty & Gag Toys',
            ],
            'Office, Schools, Businesses, Books and Movies' => [
                'Office & School Supplies',
                'Tactical Gear',
                'Business & Industrial',
                'Video Surveillance',
                'Intercom & Access Control',
                'Household Appliances',
            ],
            'Computer and Networking' => [
                'Computer Accessories',
                'Computer Components',
                'Drives & Storages',
                'Keyboards, Mice & Inputs',
                'Laptops',
                'Monitors',
                'Networking & Communications',
                'PC Brand Centers',
                'Popular Brand Tablets',
                'Printers & Supplies',
                'Projection Equipment',
                'Refurbished Laptops',
                'Refurbished Tablets',
                'Scanners',
                'Tablet PC',
                'Tablet PC Accessories',
            ],
            'Electronics' => [
                'Laptops & Computers',
                'TV & DVD Equipment',
                'Audio & Music Equipment',
                'Computer Accessories',
                'Computer Hardware',
                'Computer Monitors',
                'Headphones',
                'Networking Products',
                'Photo & Video Cameras',
                'Printers & Scanners',
                'Security & Surveillance',
                'Software',
                'Video Games',
                'Video Game Consoles',
            ],

            'Fashion' => [
                'Sunglasses',
                'Belts',
                'Hats & Caps',
                'Keychains',
                'Other Fashion Accessories',
            ],
            'Food and Beverage' => [
                'Instant drinks',
                'Coffee',
                'Snacks',
                'Biscuits',
                'Soft Drinks',
                'Functional drink',
                'Teas',
                'Flower Tea',
                'Healthy Tea',
                'Tea Leaf',
            ],
            'Hair products, Health and Beauty' => [
                'Bath & Body',
                'Fragrances',
                'Hair Beauty',
                'Make-Up',
                'Sexual Wellness',
                'Skincare',
                'Tobacco Accessories',
                'Tools & Accessories',
                'Vitamins & Supplements',
            ],
            'Homes, household Appliances, Lighting and Gardens' => [
                'Furniture',
                'Garden Supplies',
                'Home Accessories',
                'Home Appliances',
                'Kitchen Appliances',
                'Kitchenware & Cookware',
                'Household Chemicals',
            ],
            'Industrial, Medical and Construction Tools, Equipment and Machinery' => [
                'Building Materials',
                'Doors',
                'Electrical Equipment',
                'Electrical Hand Tools',
                'Hand Tools',
                'Measuring & Layout Tools',
                'Plumbing & Water Supply',
                'Solar Energy',
                'Windows',
                'Industrial Ovens',
                'Manufacturing Equipment',
                'Manufacturing Materials',
                'Medical Supplies & Equipment',
                'Printing Equipment',
                'Restaurant & Catering Equipment',
                'Safetywear & Equipment',
                'Salon Equipment',
                'Stage Lighting & Effects',
                'Stationery',
                'Store Equipment',
                'Other Repair & Construction Items',
            ],
            'Mobile Phones and Accessories, Tablets' => [
                'Mobile Phones',
                'Accessories for Mobile Phones & Tablets',
                'Smart Watches & Trackers',
                'Tablets',
            ],
            'Music and Musical instruments' => [
                'Brass',
                'Chinese Musical Instruments',
                'Guitar',
                'Harmonicas',
                'Keyboards',
                'Percussion',
                'Stage Lighting',
            ],
            'Properties' => [
                'Houses & Apartments for Sale',
                'Land & Plots for Rent',
                'Land & Plots for Sale',
                'Commercial Property for Rent',
                'Commercial Property for Sale',
                'Event Centres, Venues & Workstations',
                'Short Let Property',
            ],
            'Security and Surveillance' => [
                'Security & Surveillance',
                'CCTV cameras',
                'Hunting Trail Camera',
                'Intercom & Access Control',
                'IP Surveillance',
                'Locksmith Supplies',
                'Mini Cameras',
                'Mini Cameras & Supports',
                'Roadway Safety',
                'Security Accessories',
                'Security Alarm system',
                'Smart Home Security System',
                'Smart Home Systems',
                'Video Surveillance',
                'Other Security Product',
            ],
            'Services, Jobs and Careers' => [
                'Accounting & Finance Jobs',
                'Advertising & Marketing Jobs',
                'Arts & Entertainment Jobs',
                'Childcare & Babysitting Jobs',
                'Clerical & Administrative Jobs',
                'Computing & IT Jobs',
                'Construction & Skilled Trade Jobs',
                'Consulting & Strategy Jobs',
                'Customer Services Jobs',
                'Driver Jobs',
                'Engineering & Architecture Jobs',
                'Farming & Veterinary Jobs',
                'Gardening & Landscaping Jobs',
                'Health & Beauty Jobs',
                'Healthcare & Nursing Jobs',
                'Hotel Jobs',
                'Housekeeping & Cleaning Jobs',
                'Human Resources Jobs',
                'Internship Jobs',
                'Legal Jobs',
                'Logistics & Transportation Jobs',
                'Management Jobs',
                'Manual Labour Jobs',
                'Manufacturing Jobs',
                'Mining Industry Jobs',
                'Office Jobs',
                'Part-Time & Weekend Jobs',
                'Quality Control & Assurance Jobs',
                'Research & Survey Jobs',
                'Restaurant & Bar Jobs',
                'Retail Jobs',
                'Sales & Telemarketing Jobs',
                'Security Jobs',
                'Sports Club Jobs',
                'Teaching Jobs',
                'Technology Jobs',
                'Travel & Tourism Jobs',
                'Other Jobs',
            ],
            'Sports and outdoors' => [
                'Athletic & Outdoor Apparel, Shoes',
                'Cycling',
                'Athletic & Outdoor Accs',
                'Outdoor Gear',
                'Other Sports',
            ],
            'Vehicles' => [
                'Cars',
                'Buses & Microbuses',
                'Heavy Equipment',
                'Motorcycles & Scooters',
                'Trucks & Trailers',
                'Vehicle Parts & Accessories',
                'Watercraft & Boats',
            ],
            'Wedding, party and events' => [
                'Wedding , Party & Events',
                '2019 Prom Dresses',
                '48-hour Shipping',
                "Bridesmaids' & Formal Dresses",
                'Custom Dresses',
                "Designers' Dress Fabric & Accessories",
                'Groom Wear',
                'High-end Wedding Boutiques',
                'Kids Formal Wear',
                "Men's Party Wear",
                'Mother of the Bride Dresses',
                'Party 2019',
                'Party Dress',
                'Special Occasion Dresses',
                'Wedding & Party Shoes',
                'Wedding & Party Supplies',
                'Wedding Accessories',
                'Wedding Dresses',
                'Other Wedding Apparel',
            ],
            'Everything Else' => [],
        ];

        foreach ($categories as $key => $category) {
            $createdCategory = Category::create(['name' => $key]);

            foreach ($category as $item) {
                $createdCategory->subCategories()->create(['name' => $item]);
            }
        }
    }
}
